## import

In [ ]:
import numpy as np
from numpy import sin, cos, pi

## Define functions

In [17]:
def Rz(a):
    rot = np.array([[cos(a), -sin(a), 0,],
                    [sin(a),  cos(a),  0],
                    [     0,       0,  1],])
    return rot

def Ry(a):
    rot = np.array([[ cos(a), 0, sin(a)],
                    [      0, 1,      0],
                    [-sin(a), 0, cos(a)],])
    return rot

def Rx(a):
    rot = np.array([[1,      0,      0],
                    [0, cos(a),-sin(a)],
                    [0, sin(a), cos(a)],])
    return rot

def Rzyx(roll,pitch,yow):
    return Rz(yow) @ Ry(pitch) @ Rx(roll)

def Lmat(val0, val1, val2):
    L = np.diag([val0, val1, val2])
    return L

## User settings
Specify three eigenvalues

In [18]:
v0, v1, v2 = 0, 1, 2

## Main

In [20]:
L = Lmat(v0, v1, v2)
print("Target eigenvalues are %f, %f, %f" % (v0, v1, v2))

for i in range(0,10):
    print("\n%i th trial" % i)    
    
    angles = 2 * pi * np.random.rand(3)
    r = angles[0]
    p = angles[1]
    y = angles[2]
    R = Rzyx(r,p,y)
    print("angle/radian: roll= %f, pitch=%f, yow=%f" % (r,p,y))
    
    A = np.linalg.inv(R) @ L @ R
    print("Matrix")
    print(A)
    
    eigvals, _ = np.linalg.eigh(A)
    print("Check eigenvalues of A below")
    print(np.round(eigvals,0))

Target eigenvalues are 0.000000, 1.000000, 2.000000

0 th trial
angle/radian: roll= 1.374613, pitch=0.481061, yow=5.735627
Matrix
[[ 0.64121853 -0.77243495  0.24823651]
 [-0.77243495  1.51693639  0.36227435]
 [ 0.24823651  0.36227435  0.84184507]]
Check eigenvalues of A below
[0. 1. 2.]

1 th trial
angle/radian: roll= 1.544729, pitch=4.628659, yow=4.683226
Matrix
[[ 1.99299967e+00 -8.34454887e-02  2.62712130e-04]
 [-8.34454887e-02  1.00395354e+00  5.51991374e-02]
 [ 2.62712130e-04  5.51991374e-02  3.04679316e-03]]
Check eigenvalues of A below
[-0.  1.  2.]

2 th trial
angle/radian: roll= 1.169842, pitch=4.890705, yow=3.023256
Matrix
[[ 1.93751677  0.31107433  0.15445569]
 [ 0.31107433  0.29790761 -0.40709725]
 [ 0.15445569 -0.40709725  0.76457562]]
Check eigenvalues of A below
[-0.  1.  2.]

3 th trial
angle/radian: roll= 0.529708, pitch=1.836064, yow=4.321350
Matrix
[[1.92128312 0.06668478 0.2967215 ]
 [0.06668478 0.6430502  0.51008389]
 [0.2967215  0.51008389 0.43566668]]
Check eigen