# About this notebook
- 任意の0以上の固有値を持つ、3次の実対称行列をいくつか生成するプログラム。
- 行列のスペクトル分解に基づいている。(例えば[このノート](http://www.math.s.chiba-u.ac.jp/~nagisa/lecture04/fa3.pdf)参照)。
- ここでは実対称行列を生成しているが、エルミート行列にも拡張可能（なはず）。

## Import
numpyモジュールと、このノートブックでよく使う関数のインポート

In [33]:
import numpy as np
from numpy import sin, cos, pi

## Define functions
ロール・ピッチ・ヨー回転行列の定義

In [41]:
def _Rz(a):
    """Rotation matrix along z axis."""
    rot = np.array([[cos(a), -sin(a), 0,],
                    [sin(a),  cos(a),  0],
                    [     0,       0,  1],])
    return rot

def _Ry(a):
    """Rotation matrix along y axis."""
    rot = np.array([[ cos(a), 0, sin(a)],
                    [      0, 1,      0],
                    [-sin(a), 0, cos(a)],])
    return rot

def _Rx(a):
    """Rotation matrix along x axis."""
    rot = np.array([[1,      0,      0],
                    [0, cos(a),-sin(a)],
                    [0, sin(a), cos(a)],])
    return rot

def Rzyx(roll,pitch,yow):
    """Roll-pitch-yow rotation matrix.
    
    https://watako-lab.com/2019/01/23/roll_pitch_yaw/
    """
    return _Rz(yow) @ _Ry(pitch) @ _Rx(roll)

## User settings
3つの固有値を定義する (値はゼロ以上とすること。実対称行列の固有値はゼロ以上だから。)

In [35]:
v0, v1, v2 = 0, 1, 2

## Main

In [36]:
print("Target eigenvalues are %f, %f, %f" % (v0, v1, v2))

Target eigenvalues are 0.000000, 1.000000, 2.000000


In [39]:
###############################
## Non-rotation case
###############################
# define orthonormal basis sets
e0 = np.array([1,0,0])
e1 = np.array([0,1,0])
e2 = np.array([0,0,1])

# obtain real symmetric matrix based on spectral decomposition
A = v0 * np.outer(e0, e0) + v1 * np.outer(e1, e1) + v2 * np.outer(e2, e2)
print("Matrix A")
print(A)

# diagonalize A for confirmation
eigvals, _ = np.linalg.eigh(A)
print("Check eigenvalues of A")
print(eigvals)

Matrix A
[[0 0 0]
 [0 1 0]
 [0 0 2]]
Check eigenvalues of A
[0. 1. 2.]


In [40]:
#######################
## Rotate basis sets
#######################
for i in range(0,10):
    print("\n%i th trial" % i)    
    
    # choose roll-pitch-yow angles randomly, and define rotation matrix
    angles = 2 * pi * np.random.rand(3)
    r = angles[0]
    p = angles[1]
    y = angles[2]
    R = Rzyx(r,p,y)
    print("angle/radian: roll= %f, pitch=%f, yow=%f" % (r,p,y))
        
    # basis set vectors after rotation
    e0 = np.dot(R, e0)
    e1 = np.dot(R, e1)
    e2 = np.dot(R, e2)

    # obtain real symmetric matrix based on spectral decomposition
    A = v0 * np.outer(e0, e0) + v1 * np.outer(e1, e1) + v2 * np.outer(e2, e2)
    print("Matrix A")
    print(A)
    
    # diagonalize A for confirmation
    eigvals, _ = np.linalg.eigh(A)
    print("Check eigenvalues of A")
    print(np.round(eigvals,0))


0 th trial
angle/radian: roll= 2.550307, pitch=3.535900, yow=4.310497
Matrix A
[[ 1.27633002 -0.25871801 -0.6276033 ]
 [-0.25871801  0.28370895 -0.38429241]
 [-0.6276033  -0.38429241  1.43996103]]
Check eigenvalues of A
[-0.  1.  2.]

1 th trial
angle/radian: roll= 4.577157, pitch=2.489039, yow=4.384429
Matrix A
[[ 1.0565497  -0.76939619 -0.02071878]
 [-0.76939619  1.01629278 -0.63499257]
 [-0.02071878 -0.63499257  0.92715752]]
Check eigenvalues of A
[-0.  1.  2.]

2 th trial
angle/radian: roll= 0.294251, pitch=4.389186, yow=6.206835
Matrix A
[[ 0.59666477  0.76780879  0.01031123]
 [ 0.76780879  1.24829196 -0.53495797]
 [ 0.01031123 -0.53495797  1.15504327]]
Check eigenvalues of A
[-0.  1.  2.]

3 th trial
angle/radian: roll= 3.483982, pitch=5.946035, yow=3.223795
Matrix A
[[ 0.884544   -0.60892287  0.23059646]
 [-0.60892287  1.4805011   0.62233717]
 [ 0.23059646  0.62233717  0.6349549 ]]
Check eigenvalues of A
[0. 1. 2.]

4 th trial
angle/radian: roll= 2.076405, pitch=5.030494, yow=5